version: "3.7"
services:
  das_mongo:
    image: "mongo:6.0.5"
    container_name: das_mongodb
    restart: always
    volumes:
        - "./db/data/db-files:/data/db"
        - "./db/init/:/docker-entrypoint-initdb.d/"

    ports:
      - "27017:27017"



  das_data:
    container_name: das_data
    restart: always

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app

    environment:
      - NODE_ENV="development"
      - APP_PORT=3000
      - APP_NAME="Dashboard Starter Data"
      - API_PREFIX=das-api
      - APP_FALLBACK_LANGUAGE=en
      - APP_HEADER_LANGUAGE=x-custom-lang
      - FRONTEND_DOMAIN=http://localhost:3000
      - BACKEND_DOMAIN=http://localhost:3000
      - MONGO_URI=mongodb://das_mongo:27017
      - MONGO_DB_NAME=das_data


    ports:
      - "3000:3000"
      - "9229:9229"



